### ISSUE TITLE
请问有windows版本么？可以分享么？

### ISSUE THREAD

**Issue by zxp771** [fylimas/YSF#2]

**Comment by fylimas** [comment]
已经更新适配了windows，但是我手头没有windows电脑，你看看是否可用

**Comment by zxp771** [comment]
感谢您的回复，我上午试着自己改了一下nsfcysf文件，已经可以使用了。非常感谢您的分享发自我的 iPhone在 2023年1月3日，14:31，Fangyuan Li ***@***.***> 写道：﻿
已经更新适配了windows，但是我手头没有windows电脑，你看看是否可用
