### ISSUE TITLE
三级标题（subsubsection）的问题

### ISSUE THREAD

**Issue by zxp771** [fylimas/YSF#3]
![1673225648247](https://user-images.githubusercontent.com/35118859/211227399-2f516cc0-7a89-454e-8226-49d551c0ca9e.png)
![1673225655316](https://user-images.githubusercontent.com/35118859/211227410-03cf8c4d-c93a-48e7-b6cc-707afff6bcb2.png)
您好，请问三级标题的编号如何更改成类似于正常论文1.2.1这样的形式？
找了一下nsfcysf文件，没发现能修改的地方。

**Comment by zxp771** [comment]
已找到方法

**Comment by wangsiwei2010** [comment]
> 已找到方法

您好，请问三级标题如何设置呢？

**Comment by wangsiwei2010** [comment]
> 已找到方法



> 已找到方法

您好，请问三级标题如何设置呢？
