### ISSUE TITLE
参考文献年份在最后

### ISSUE THREAD

**Issue by nil-is-lin** [fylimas/YSF#4]
我这里是windows环境，跑了一下，参考文献的年份在最后。
![image](https://user-images.githubusercontent.com/6971475/212658720-d5f74056-ca56-4b8e-8ded-0473a8a26f5f.png)

**Comment by fylimas** [comment]
不同期刊对参考文献格式要求不同，但是国基金模版对参考文献的格式没有特定要求，全文保持一致就好啦

**Comment by nil-is-lin** [comment]
好的，感谢感谢。我还以为中文一般都是按gbt7714-2015来的 :)
