### ISSUE TITLE
公式编号问题

### ISSUE THREAD

**Issue by zxp771** [fylimas/YSF#6]
![image](https://user-images.githubusercontent.com/35118859/218446635-43e4e746-dd7e-407b-a6e3-2ea5e18907d8.png)
您好，我想请问一下这个公式编号顺序可以在哪儿改么？找了半天没找到。为什么公式编号是按1.1这么开始，而不能直接从1开始

**Comment by fylimas** [comment]
抱歉现在才看到，大家想要的公式编号的格式往往不一样。
考虑到申请书中，写多了公式也不好，因此，公式编号建议用\tag{}解决吧

**Comment by zxp771** [comment]
感谢您的回复，我确实就是用tag解决的发自我的 iPhone在 2023年11月23日，12:04，Fangyuan Li ***@***.***> 写道：﻿
抱歉现在才看到，大家想要的公式编号的格式往往不一样。
考虑到申请书中，写多了公式也不好，因此，公式编号建议用\tag{}解决吧
